services:
    pyhton:
        build: ./Docker
        tty: true
        volumes:
            - ./src:/src
            # - ./cache:/root/.cache/
        runtime: nvidia
        env_file:
            - ./.env
        ports:
            - 8000:8000
        command: ["python","app.py"]
